version: 2
 
models:
    - name: demo_new
      description: "A starter dbt model"
      columns:
          - name:  C_CUSTKEY
            description: "The primary key for this table"
            tests:
                - not_null_demo
                - unique_records
               
                
          - name:  C_NAME
            description: "The primary key for this table"
            tests:
                - not_null_demo
                - unique_records
                
          - name:  C_PHONE
            description: "The primary key for this table"
            tests:
                - unique_records                
                
               
