SELECT CONCAT(FIRST_NAME,last_name) AS EMPLOYEE_NAME,EMPLOYEE_ID,D.DEPARTMENT_ID,DEPARTMENT_NAME,SUM(SALARY) AS EMP_SALARY
FROM {{ref('emp')}} E INNER JOIN {{ref('departments')}} D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
GROUP BY EMPLOYEE_NAME,EMPLOYEE_ID,D.DEPARTMENT_ID,DEPARTMENT_NAME